import { GameValues } from './types';

export const GaragesBlock: GameValues = [
   { type: 'GarageCar', address: 0x0027, name: 'garageCars', arrayLength: 80 },
];

export const ScriptBlock: GameValues = [
   { type: 'byte', address: 0x0704, name: 'intSection' },
   { type: 'byte', address: 0x0714, name: 'sweetSection' },
   { type: 'byte', address: 0x0718, name: 'ryderSection' },
   { type: 'byte', address: 0x071c, name: 'smokeSection' },
   { type: 'byte', address: 0x0720, name: 'strapSection' },
   { type: 'byte', address: 0x0724, name: 'crashSection' },
   { type: 'byte', address: 0x0728, name: 'cesarSection' },
   { type: 'byte', address: 0x072c, name: 'la1finSection' },
   { type: 'byte', address: 0x07b0, name: 'truSection' },
   { type: 'byte', address: 0x07b4, name: 'bcesarSection' },
   { type: 'byte', address: 0x07b8, name: 'bcrashSection' },
   { type: 'byte', address: 0x0878, name: 'garageSection' },
   { type: 'byte', address: 0x087c, name: 'zeroSection' },
   { type: 'byte', address: 0x0880, name: 'wuziSection' },
   { type: 'byte', address: 0x0884, name: 'stealSection' },
   { type: 'byte', address: 0x0888, name: 'syndSection' },
   { type: 'byte', address: 0x088c, name: 'scrashSection' },
   { type: 'byte', address: 0x0948, name: 'desertSection' },
   { type: 'byte', address: 0x0958, name: 'casinoSection' },
   { type: 'byte', address: 0x095c, name: 'vcrashSection' },
   { type: 'byte', address: 0x0960, name: 'docSection' },
   { type: 'byte', address: 0x0964, name: 'heistSection' },
   { type: 'byte', address: 0x09cc, name: 'mansionSection' },
   { type: 'byte', address: 0x09d0, name: 'groveSection' },
   { type: 'byte', address: 0x09d8, name: 'riotSection' },
   { type: 'byte', address: 0x0b2c, name: 'cat1' },
   { type: 'byte', address: 0x0b30, name: 'cat2' },
   { type: 'byte', address: 0x0b34, name: 'cat3' },
   { type: 'byte', address: 0x0b38, name: 'cat4' },
   { type: 'byte', address: 0x0b38, name: 'cat4Section' },
   { type: 'byte', address: 0x01b0, name: 'drivingSchool.360' },
   { type: 'byte', address: 0x01a8, name: 'drivingSchool.180' },
   { type: 'byte', address: 0x018c, name: 'drivingSchool.WhipAndTerminate' },
   { type: 'byte', address: 0x0184, name: 'drivingSchool.PopAndControl' },
   { type: 'byte', address: 0x017c, name: 'drivingSchool.BurnAndLap' },
   { type: 'byte', address: 0x01a0, name: 'drivingSchool.ConeCoil' },
   { type: 'byte', address: 0x0170, name: 'drivingSchool.90' },
   { type: 'byte', address: 0x0198, name: 'drivingSchool.WheelieWeave' },
   { type: 'byte', address: 0x0174, name: 'drivingSchool.SpinAndGo' },
   { type: 'byte', address: 0x019c, name: 'drivingSchool.PITManeuver' },
   { type: 'byte', address: 0x0194, name: 'drivingSchool.AlleyOop' },
   { type: 'byte', address: 0x0188, name: 'drivingSchool.CitySlicking' },
   { type: 'byte', address: 0x1e5c, name: 'flyingSchool.Takeoff' },
   { type: 'byte', address: 0x1e60, name: 'flyingSchool.LandPlane' },
   { type: 'byte', address: 0x1e64, name: 'flyingSchool.CircleAirstrip' },
   {
      type: 'byte',
      address: 0x1e68,
      name: 'flyingSchool.CircleAirstripAndLand',
   },
   { type: 'byte', address: 0x1e6c, name: 'flyingSchool.HelicopterTakeoff' },
   { type: 'byte', address: 0x1e70, name: 'flyingSchool.LandHelicopter' },
   { type: 'byte', address: 0x1e74, name: 'flyingSchool.DestroyTargets' },
   { type: 'byte', address: 0x1e78, name: 'flyingSchool.LoopTheLoop' },
   { type: 'byte', address: 0x1e7c, name: 'flyingSchool.BarrelRoll' },
   { type: 'byte', address: 0x1e80, name: 'flyingSchool.ParachuteOntoTarget' },
   { type: 'int', address: 0x1eb0, name: 'boatSchool.BasicSeamanship' },
   { type: 'int', address: 0x1eb4, name: 'boatSchool.PlotACourse' },
   { type: 'int', address: 0x1eb8, name: 'boatSchool.FreshSlalom' },
   { type: 'int', address: 0x1ebc, name: 'boatSchool.FlyingFish' },
   { type: 'int', address: 0x1ec0, name: 'boatSchool.LandSeaAndAir' },
   { type: 'byte', address: 0x21dc, name: 'bikeSchool.360' },
   { type: 'byte', address: 0x21e0, name: 'bikeSchool.180' },
   { type: 'byte', address: 0x21d4, name: 'bikeSchool.TheWheelie' },
   { type: 'byte', address: 0x21e4, name: 'bikeSchool.JumpAndStop' },
   { type: 'byte', address: 0x21d8, name: 'bikeSchool.TheStoppie' },
   { type: 'byte', address: 0x21e8, name: 'bikeSchool.JumpAndStoppie' },
];

export const StuntJumpBlock: GameValues = [
   { type: 'dword', address: 0x0000, name: 'numberOfUniqueStuntJumps' },
   { type: 'StuntJump', address: 0x0004, arrayLength: 70, name: 'stuntJumps' },
];

export const PickUpsBlock: GameValues = [
   { type: 'PickUp', address: 0x0000, arrayLength: 620, name: 'pickUps' },
];

export const PlayersAndObjectsBlock: GameValues = [
   { type: 'dword', address: 0x00, name: 'numberOfPlayers' },
   { type: 'Player', address: 0x04, arrayLength: 1, name: 'players' },
];

export const MetaBlock: GameValues = [
   { type: 'dword', address: 0x0000, name: 'versionID' },
   { type: 'char', address: 0x0004, arrayLength: 100, name: 'saveName' },
   { type: 'byte', address: 0x0084, name: 'currentMonth' },
   { type: 'byte', address: 0x0085, name: 'currentDay' },
   { type: 'byte', address: 0x0088, name: 'currentWeekday' },
   { type: 'byte', address: 0x0086, name: 'currentHour' },
   { type: 'byte', address: 0x0087, name: 'currentMinute' },
   { type: 'byte', address: 0x0090, name: 'isCheater' },
   { type: 'byte', address: 0x0135, name: 'isTaxisDone' },
   { type: 'byte', address: 0x0136, name: 'isProstitutesDone' },
];

export const PlayerInfoBlock: GameValues = [
   { type: 'dword', address: 0x04, name: 'money' },
   { type: 'byte', address: 0x20, name: 'hasInfinityRun' },
   { type: 'byte', address: 0x21, name: 'hasFastReload' },
   { type: 'byte', address: 0x22, name: 'hasFireproof' },
   { type: 'byte', address: 0x23, name: 'maxHealth' },
   { type: 'byte', address: 0x24, name: 'maxArmor' },
];

export const TagsBlock: GameValues = [
   { type: 'dword', name: 'totalTags', address: 0x00 },
   { type: 'byte', name: 'tags', address: 0x04, arrayLength: 100 },
];

export const StatsBlock: GameValues = [
   { type: 'float', address: 0x000c, name: 'footDistance' },
   { type: 'float', address: 0x0010, name: 'carDistance' },
   { type: 'float', address: 0x0014, name: 'motorbikeDistance' },
   { type: 'float', address: 0x0018, name: 'boatDistance' },
   { type: 'float', address: 0x001c, name: 'golfCartDistance' },
   { type: 'float', address: 0x0020, name: 'helicopterDistance' },
   { type: 'float', address: 0x0024, name: 'planeDistance' },
   { type: 'float', address: 0x0068, name: 'swimmingDistance' },
   { type: 'float', address: 0x006c, name: 'bicycleDistance' },
   { type: 'float', address: 0x0070, name: 'treadmillDistance' },
   { type: 'float', address: 0x0074, name: 'exerciseBikeDistance' },
   { type: 'byte', address: 0x01a8, name: 'uniqueJumpsFound' },
   { type: 'byte', address: 0x01ac, name: 'uniqueJumpsDone' },
   { type: 'float', address: 0x0034, name: 'weaponBudget' },
   { type: 'float', address: 0x0038, name: 'fashionBudget' },
   { type: 'float', address: 0x003c, name: 'propertyBudget' },
   { type: 'float', address: 0x0040, name: 'repairPaintBudget' },
   { type: 'float', address: 0x0050, name: 'foodBudget' },
   { type: 'float', address: 0x0078, name: 'tatooBudget' },
   { type: 'float', address: 0x007c, name: 'hairdressingBudget' },
   { type: 'float', address: 0x0084, name: 'prostituteBudget' },
   { type: 'float', address: 0x00dc, name: 'carModificationBudget' },
   { type: 'float', address: 0x0090, name: 'pimpingMoney' },
   { type: 'float', address: 0x0098, name: 'gamblingMoney' },
   { type: 'float', address: 0x00a4, name: 'burglaryMoney' },
   { type: 'byte', address: 0x00b8, name: 'benchpressMaxWeight' },
   { type: 'byte', address: 0x00bc, name: 'dumbbellsMaxWeight' },
   { type: 'float', address: 0x0054, name: 'fat' },
   { type: 'float', address: 0x0058, name: 'stamina' },
   { type: 'float', address: 0x005c, name: 'muscle' },
   { type: 'float', address: 0x0060, name: 'maxHealth' },
   { type: 'float', address: 0x0100, name: 'respect' },
   { type: 'float', address: 0x0140, name: 'sexAppeal' },
   { type: 'float', address: 0x0144, name: 'gambling' },
   { type: 'int', address: 0x01e8, name: 'drivingSkill' },
   { type: 'float', address: 0x0114, name: 'pistol' },
   { type: 'float', address: 0x0118, name: 'silencedPistol' },
   { type: 'float', address: 0x011c, name: 'desertEagel' },
   { type: 'float', address: 0x0120, name: 'shotgun' },
   { type: 'float', address: 0x0124, name: 'sawnOFF' },
   { type: 'float', address: 0x0128, name: 'combatShotgun' },
   { type: 'float', address: 0x012c, name: 'machinePistol' },
   { type: 'float', address: 0x0130, name: 'SMG' },
   { type: 'float', address: 0x0134, name: 'AK47' },
   { type: 'float', address: 0x0138, name: 'M4' },
   { type: 'float', address: 0x013c, name: 'rifle' },
   { type: 'int', address: 0x02b0, name: 'pimpingLevel' },
   { type: 'float', address: 0x02e4, name: 'flyingSkill' },
   { type: 'float', address: 0x02ec, name: 'lungCapacity' },
   { type: 'int', address: 0x02fc, name: 'bikeSkill' },
   { type: 'int', address: 0x0300, name: 'cyclingSkill' },
   { type: 'float', address: 0x030c, name: 'luck' },
   { type: 'byte', address: 0x032c, name: 'horseshoesCollected' },
   { type: 'byte', address: 0x0334, name: 'oystersCollected' },
   { type: 'int', address: 0x0170, name: 'headshots' },
   { type: 'int', address: 0x0180, name: 'daysPassed' },
   { type: 'int', address: 0x01b0, name: 'missionAttempts' },
   { type: 'int', address: 0x01b4, name: 'missionsPassed' },
];
